# taken from https://github.com/geerlingguy/ansible-role-docker/blob/master tamplate
---
- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool