name: devops-labs

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
        
      - name: Caching dependencies
        uses: actions/cache@v2
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Installing dependencies
        working-directory: "app_python"
        run: pip install -r requirements.txt
      
      - name: Linting
        run: flake8 .
      
      - name: Runing tests
        run: pytest

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checking for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with: 
          args:
            -snyk
            -test app_python 
            --package-manager=pip
            --skip-unresolved
  
  docker:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Caching Docker layers
        uses: actions/cache@v2
        with: 
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: ${{ runner.os }}-docker-
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Build and Push image
        uses: docker/build-push-action@v5
        with: 
          context: ./app_python
          file: app_python/Dockerfile
          push: true
          tags: vikono/devops:latest 
        
      